% -------------------------------------------------------------------
%  Generated by MATLAB on 20-Dec-2022 03:12:18
%  MATLAB version: 9.13.0.2105380 (R2022b) Update 2
% -------------------------------------------------------------------
                                 

Files = struct;
Files(1, 1).name = 'Accelerometer Data 2019-06-28 14-00-01.txt';
Files(1, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proyec' ...
                      'to'];
Files(1, 1).date = '10-Ara-2022 15:18:56';
Files(1, 1).bytes = 347211;
Files(1, 1).isdir = false;
Files(1, 1).datenum = 738865.63814814819;
Files(2, 1).name = 'Accelerometer Data 2019-06-28 14-37-42.txt';
Files(2, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proyec' ...
                      'to'];
Files(2, 1).date = '10-Ara-2022 15:18:57';
Files(2, 1).bytes = 347211;
Files(2, 1).isdir = false;
Files(2, 1).datenum = 738865.63815972221;
Files(3, 1).name = 'D_dribble1.txt';
Files(3, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proyec' ...
                      'to'];
Files(3, 1).date = '10-Ara-2022 15:18:57';
Files(3, 1).bytes = 66931;
Files(3, 1).isdir = false;
Files(3, 1).datenum = 738865.63815972221;
Files(4, 1).name = 'D_dribble2.txt';
Files(4, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proyec' ...
                      'to'];
Files(4, 1).date = '10-Ara-2022 15:18:57';
Files(4, 1).bytes = 66346;
Files(4, 1).isdir = false;
Files(4, 1).datenum = 738865.63815972221;
Files(5, 1).name = 'D_dribble3.txt';
Files(5, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proyec' ...
                      'to'];
Files(5, 1).date = '10-Ara-2022 15:18:57';
Files(5, 1).bytes = 67891;
Files(5, 1).isdir = false;
Files(5, 1).datenum = 738865.63815972221;
Files(6, 1).name = 'D_hold1.txt';
Files(6, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proyec' ...
                      'to'];
Files(6, 1).date = '10-Ara-2022 15:18:57';
Files(6, 1).bytes = 33043;
Files(6, 1).isdir = false;
Files(6, 1).datenum = 738865.63815972221;
Files(7, 1).name = 'D_hold2.txt';
Files(7, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proyec' ...
                      'to'];
Files(7, 1).date = '10-Ara-2022 15:18:57';
Files(7, 1).bytes = 37003;
Files(7, 1).isdir = false;
Files(7, 1).datenum = 738865.63815972221;
Files(8, 1).name = 'D_hold3.txt';
Files(8, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proyec' ...
                      'to'];
Files(8, 1).date = '10-Ara-2022 15:18:57';
Files(8, 1).bytes = 35378;
Files(8, 1).isdir = false;
Files(8, 1).datenum = 738865.63815972221;
Files(9, 1).name = 'D_pass1.txt';
Files(9, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proyec' ...
                      'to'];
Files(9, 1).date = '10-Ara-2022 15:18:57';
Files(9, 1).bytes = 41248;
Files(9, 1).isdir = false;
Files(9, 1).datenum = 738865.63815972221;
Files(10, 1).name = 'D_pass2.txt';
Files(10, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(10, 1).date = '10-Ara-2022 15:18:57';
Files(10, 1).bytes = 38442;
Files(10, 1).isdir = false;
Files(10, 1).datenum = 738865.63815972221;
Files(11, 1).name = 'D_pass3.txt';
Files(11, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(11, 1).date = '10-Ara-2022 15:18:58';
Files(11, 1).bytes = 35914;
Files(11, 1).isdir = false;
Files(11, 1).datenum = 738865.63817129633;
Files(12, 1).name = 'D_pass4.txt';
Files(12, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(12, 1).date = '10-Ara-2022 15:18:58';
Files(12, 1).bytes = 52836;
Files(12, 1).isdir = false;
Files(12, 1).datenum = 738865.63817129633;
Files(13, 1).name = 'D_pass5.txt';
Files(13, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(13, 1).date = '10-Ara-2022 15:18:58';
Files(13, 1).bytes = 39453;
Files(13, 1).isdir = false;
Files(13, 1).datenum = 738865.63817129633;
Files(14, 1).name = 'D_pass6.txt';
Files(14, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(14, 1).date = '10-Ara-2022 15:18:58';
Files(14, 1).bytes = 41747;
Files(14, 1).isdir = false;
Files(14, 1).datenum = 738865.63817129633;
Files(15, 1).name = 'D_pickup1.txt';
Files(15, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(15, 1).date = '10-Ara-2022 15:18:58';
Files(15, 1).bytes = 93309;
Files(15, 1).isdir = false;
Files(15, 1).datenum = 738865.63817129633;
Files(16, 1).name = 'D_pickup2.txt';
Files(16, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(16, 1).date = '10-Ara-2022 15:18:58';
Files(16, 1).bytes = 68878;
Files(16, 1).isdir = false;
Files(16, 1).datenum = 738865.63817129633;
Files(17, 1).name = 'D_pickup3.txt';
Files(17, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(17, 1).date = '10-Ara-2022 15:18:58';
Files(17, 1).bytes = 63510;
Files(17, 1).isdir = false;
Files(17, 1).datenum = 738865.63817129633;
Files(18, 1).name = 'D_pickup4.txt';
Files(18, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(18, 1).date = '10-Ara-2022 15:18:58';
Files(18, 1).bytes = 63195;
Files(18, 1).isdir = false;
Files(18, 1).datenum = 738865.63817129633;
Files(19, 1).name = 'D_pickup5.txt';
Files(19, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(19, 1).date = '10-Ara-2022 15:18:58';
Files(19, 1).bytes = 68864;
Files(19, 1).isdir = false;
Files(19, 1).datenum = 738865.63817129633;
Files(20, 1).name = 'D_shoot1.txt';
Files(20, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(20, 1).date = '10-Ara-2022 15:18:58';
Files(20, 1).bytes = 22152;
Files(20, 1).isdir = false;
Files(20, 1).datenum = 738865.63817129633;
Files(21, 1).name = 'D_shoot2.txt';
Files(21, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(21, 1).date = '10-Ara-2022 15:18:58';
Files(21, 1).bytes = 25389;
Files(21, 1).isdir = false;
Files(21, 1).datenum = 738865.63817129633;
Files(22, 1).name = 'D_shoot3.txt';
Files(22, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(22, 1).date = '10-Ara-2022 15:18:58';
Files(22, 1).bytes = 23907;
Files(22, 1).isdir = false;
Files(22, 1).datenum = 738865.63817129633;
Files(23, 1).name = 'D_shoot4.txt';
Files(23, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(23, 1).date = '10-Ara-2022 15:18:59';
Files(23, 1).bytes = 24198;
Files(23, 1).isdir = false;
Files(23, 1).datenum = 738865.63818287035;
Files(24, 1).name = 'D_shoot5.txt';
Files(24, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(24, 1).date = '10-Ara-2022 15:18:59';
Files(24, 1).bytes = 24764;
Files(24, 1).isdir = false;
Files(24, 1).datenum = 738865.63818287035;
Files(25, 1).name = 'Jc_dribble1.txt';
Files(25, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(25, 1).date = '10-Ara-2022 15:18:59';
Files(25, 1).bytes = 71708;
Files(25, 1).isdir = false;
Files(25, 1).datenum = 738865.63818287035;
Files(26, 1).name = 'Jc_dribble2.txt';
Files(26, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(26, 1).date = '10-Ara-2022 15:18:59';
Files(26, 1).bytes = 76507;
Files(26, 1).isdir = false;
Files(26, 1).datenum = 738865.63818287035;
Files(27, 1).name = 'Jc_dribble3.txt';
Files(27, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(27, 1).date = '10-Ara-2022 15:18:59';
Files(27, 1).bytes = 69924;
Files(27, 1).isdir = false;
Files(27, 1).datenum = 738865.63818287035;
Files(28, 1).name = 'Jc_hold1.txt';
Files(28, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(28, 1).date = '10-Ara-2022 15:18:59';
Files(28, 1).bytes = 43878;
Files(28, 1).isdir = false;
Files(28, 1).datenum = 738865.63818287035;
Files(29, 1).name = 'Jc_hold2.txt';
Files(29, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(29, 1).date = '10-Ara-2022 15:18:59';
Files(29, 1).bytes = 25687;
Files(29, 1).isdir = false;
Files(29, 1).datenum = 738865.63818287035;
Files(30, 1).name = 'Jc_hold3.txt';
Files(30, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(30, 1).date = '10-Ara-2022 15:18:59';
Files(30, 1).bytes = 30898;
Files(30, 1).isdir = false;
Files(30, 1).datenum = 738865.63818287035;
Files(31, 1).name = 'Jc_pass1.txt';
Files(31, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(31, 1).date = '10-Ara-2022 15:18:59';
Files(31, 1).bytes = 52373;
Files(31, 1).isdir = false;
Files(31, 1).datenum = 738865.63818287035;
Files(32, 1).name = 'Jc_pass2.txt';
Files(32, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(32, 1).date = '10-Ara-2022 15:18:59';
Files(32, 1).bytes = 35931;
Files(32, 1).isdir = false;
Files(32, 1).datenum = 738865.63818287035;
Files(33, 1).name = 'Jc_pass3.txt';
Files(33, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(33, 1).date = '10-Ara-2022 15:18:59';
Files(33, 1).bytes = 40981;
Files(33, 1).isdir = false;
Files(33, 1).datenum = 738865.63818287035;
Files(34, 1).name = 'Jc_pass4.txt';
Files(34, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(34, 1).date = '10-Ara-2022 15:18:59';
Files(34, 1).bytes = 37579;
Files(34, 1).isdir = false;
Files(34, 1).datenum = 738865.63818287035;
Files(35, 1).name = 'Jc_pass5.txt';
Files(35, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(35, 1).date = '10-Ara-2022 15:18:59';
Files(35, 1).bytes = 47654;
Files(35, 1).isdir = false;
Files(35, 1).datenum = 738865.63818287035;
Files(36, 1).name = 'Jc_pickup1.txt';
Files(36, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(36, 1).date = '10-Ara-2022 15:18:59';
Files(36, 1).bytes = 74619;
Files(36, 1).isdir = false;
Files(36, 1).datenum = 738865.63818287035;
Files(37, 1).name = 'Jc_pickup2.txt';
Files(37, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(37, 1).date = '10-Ara-2022 15:18:59';
Files(37, 1).bytes = 53679;
Files(37, 1).isdir = false;
Files(37, 1).datenum = 738865.63818287035;
Files(38, 1).name = 'Jc_pickup3.txt';
Files(38, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(38, 1).date = '10-Ara-2022 15:18:59';
Files(38, 1).bytes = 57939;
Files(38, 1).isdir = false;
Files(38, 1).datenum = 738865.63818287035;
Files(39, 1).name = 'Jc_pickup4.txt';
Files(39, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(39, 1).date = '10-Ara-2022 15:19:00';
Files(39, 1).bytes = 59033;
Files(39, 1).isdir = false;
Files(39, 1).datenum = 738865.63819444447;
Files(40, 1).name = 'Jc_pickup5.txt';
Files(40, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(40, 1).date = '10-Ara-2022 15:19:00';
Files(40, 1).bytes = 73940;
Files(40, 1).isdir = false;
Files(40, 1).datenum = 738865.63819444447;
Files(41, 1).name = 'Jc_shoot1.txt';
Files(41, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(41, 1).date = '10-Ara-2022 15:19:00';
Files(41, 1).bytes = 24130;
Files(41, 1).isdir = false;
Files(41, 1).datenum = 738865.63819444447;
Files(42, 1).name = 'Jc_shoot2.txt';
Files(42, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(42, 1).date = '10-Ara-2022 15:19:00';
Files(42, 1).bytes = 28665;
Files(42, 1).isdir = false;
Files(42, 1).datenum = 738865.63819444447;
Files(43, 1).name = 'Jc_shoot3.txt';
Files(43, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(43, 1).date = '10-Ara-2022 15:19:00';
Files(43, 1).bytes = 24436;
Files(43, 1).isdir = false;
Files(43, 1).datenum = 738865.63819444447;
Files(44, 1).name = 'Jc_shoot4.txt';
Files(44, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(44, 1).date = '10-Ara-2022 15:19:00';
Files(44, 1).bytes = 26029;
Files(44, 1).isdir = false;
Files(44, 1).datenum = 738865.63819444447;
Files(45, 1).name = 'Jc_shoot5.txt';
Files(45, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(45, 1).date = '10-Ara-2022 15:19:00';
Files(45, 1).bytes = 23962;
Files(45, 1).isdir = false;
Files(45, 1).datenum = 738865.63819444447;
Files(46, 1).name = 'L_dribble1.txt';
Files(46, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(46, 1).date = '10-Ara-2022 15:19:00';
Files(46, 1).bytes = 75197;
Files(46, 1).isdir = false;
Files(46, 1).datenum = 738865.63819444447;
Files(47, 1).name = 'L_dribble2.txt';
Files(47, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(47, 1).date = '10-Ara-2022 15:19:00';
Files(47, 1).bytes = 69833;
Files(47, 1).isdir = false;
Files(47, 1).datenum = 738865.63819444447;
Files(48, 1).name = 'L_dribble3.txt';
Files(48, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(48, 1).date = '10-Ara-2022 15:19:00';
Files(48, 1).bytes = 79963;
Files(48, 1).isdir = false;
Files(48, 1).datenum = 738865.63819444447;
Files(49, 1).name = 'L_hold1.txt';
Files(49, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(49, 1).date = '10-Ara-2022 15:19:00';
Files(49, 1).bytes = 36454;
Files(49, 1).isdir = false;
Files(49, 1).datenum = 738865.63819444447;
Files(50, 1).name = 'L_hold2.txt';
Files(50, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(50, 1).date = '10-Ara-2022 15:19:00';
Files(50, 1).bytes = 34927;
Files(50, 1).isdir = false;
Files(50, 1).datenum = 738865.63819444447;
Files(51, 1).name = 'L_hold3.txt';
Files(51, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(51, 1).date = '10-Ara-2022 15:19:00';
Files(51, 1).bytes = 34743;
Files(51, 1).isdir = false;
Files(51, 1).datenum = 738865.63819444447;
Files(52, 1).name = 'L_pass1.txt';
Files(52, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(52, 1).date = '10-Ara-2022 15:19:00';
Files(52, 1).bytes = 40759;
Files(52, 1).isdir = false;
Files(52, 1).datenum = 738865.63819444447;
Files(53, 1).name = 'L_pass2.txt';
Files(53, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(53, 1).date = '10-Ara-2022 15:19:00';
Files(53, 1).bytes = 35706;
Files(53, 1).isdir = false;
Files(53, 1).datenum = 738865.63819444447;
Files(54, 1).name = 'L_pass3.txt';
Files(54, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(54, 1).date = '10-Ara-2022 15:19:00';
Files(54, 1).bytes = 33147;
Files(54, 1).isdir = false;
Files(54, 1).datenum = 738865.63819444447;
Files(55, 1).name = 'L_pass4.txt';
Files(55, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(55, 1).date = '10-Ara-2022 15:19:01';
Files(55, 1).bytes = 37406;
Files(55, 1).isdir = false;
Files(55, 1).datenum = 738865.63820601848;
Files(56, 1).name = 'L_pass5.txt';
Files(56, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(56, 1).date = '10-Ara-2022 15:19:01';
Files(56, 1).bytes = 43605;
Files(56, 1).isdir = false;
Files(56, 1).datenum = 738865.63820601848;
Files(57, 1).name = 'L_pickup1.txt';
Files(57, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(57, 1).date = '10-Ara-2022 15:19:01';
Files(57, 1).bytes = 51615;
Files(57, 1).isdir = false;
Files(57, 1).datenum = 738865.63820601848;
Files(58, 1).name = 'L_pickup2.txt';
Files(58, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(58, 1).date = '10-Ara-2022 15:19:01';
Files(58, 1).bytes = 49284;
Files(58, 1).isdir = false;
Files(58, 1).datenum = 738865.63820601848;
Files(59, 1).name = 'L_pickup3.txt';
Files(59, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(59, 1).date = '10-Ara-2022 15:19:01';
Files(59, 1).bytes = 45547;
Files(59, 1).isdir = false;
Files(59, 1).datenum = 738865.63820601848;
Files(60, 1).name = 'L_pickup4.txt';
Files(60, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(60, 1).date = '10-Ara-2022 15:19:01';
Files(60, 1).bytes = 42489;
Files(60, 1).isdir = false;
Files(60, 1).datenum = 738865.63820601848;
Files(61, 1).name = 'L_pickup5.txt';
Files(61, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(61, 1).date = '10-Ara-2022 15:19:01';
Files(61, 1).bytes = 47487;
Files(61, 1).isdir = false;
Files(61, 1).datenum = 738865.63820601848;
Files(62, 1).name = 'L_shoot1.txt';
Files(62, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(62, 1).date = '10-Ara-2022 15:19:01';
Files(62, 1).bytes = 24225;
Files(62, 1).isdir = false;
Files(62, 1).datenum = 738865.63820601848;
Files(63, 1).name = 'L_shoot2.txt';
Files(63, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(63, 1).date = '10-Ara-2022 15:19:01';
Files(63, 1).bytes = 26988;
Files(63, 1).isdir = false;
Files(63, 1).datenum = 738865.63820601848;
Files(64, 1).name = 'L_shoot3.txt';
Files(64, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(64, 1).date = '10-Ara-2022 15:19:01';
Files(64, 1).bytes = 34651;
Files(64, 1).isdir = false;
Files(64, 1).datenum = 738865.63820601848;
Files(65, 1).name = 'L_shoot4.txt';
Files(65, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(65, 1).date = '10-Ara-2022 15:19:01';
Files(65, 1).bytes = 34640;
Files(65, 1).isdir = false;
Files(65, 1).datenum = 738865.63820601848;
Files(66, 1).name = 'L_shoot5.txt';
Files(66, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(66, 1).date = '10-Ara-2022 15:19:01';
Files(66, 1).bytes = 25735;
Files(66, 1).isdir = false;
Files(66, 1).datenum = 738865.63820601848;
Files(67, 1).name = 'ReadMe.txt';
Files(67, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(67, 1).date = '10-Ara-2022 15:19:01';
Files(67, 1).bytes = 2671;
Files(67, 1).isdir = false;
Files(67, 1).datenum = 738865.63820601848;
Files(68, 1).name = 'X_dribble1.txt';
Files(68, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(68, 1).date = '10-Ara-2022 15:19:01';
Files(68, 1).bytes = 75304;
Files(68, 1).isdir = false;
Files(68, 1).datenum = 738865.63820601848;
Files(69, 1).name = 'X_dribble2.txt';
Files(69, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(69, 1).date = '10-Ara-2022 15:19:01';
Files(69, 1).bytes = 64575;
Files(69, 1).isdir = false;
Files(69, 1).datenum = 738865.63820601848;
Files(70, 1).name = 'X_dribble3.txt';
Files(70, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(70, 1).date = '10-Ara-2022 15:19:01';
Files(70, 1).bytes = 77161;
Files(70, 1).isdir = false;
Files(70, 1).datenum = 738865.63820601848;
Files(71, 1).name = 'X_hold1.txt';
Files(71, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(71, 1).date = '10-Ara-2022 15:19:01';
Files(71, 1).bytes = 47849;
Files(71, 1).isdir = false;
Files(71, 1).datenum = 738865.63820601848;
Files(72, 1).name = 'X_hold2.txt';
Files(72, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(72, 1).date = '10-Ara-2022 15:19:02';
Files(72, 1).bytes = 31210;
Files(72, 1).isdir = false;
Files(72, 1).datenum = 738865.63821759261;
Files(73, 1).name = 'X_hold3.txt';
Files(73, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(73, 1).date = '10-Ara-2022 15:19:02';
Files(73, 1).bytes = 31870;
Files(73, 1).isdir = false;
Files(73, 1).datenum = 738865.63821759261;
Files(74, 1).name = 'X_pass1.txt';
Files(74, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(74, 1).date = '10-Ara-2022 15:19:02';
Files(74, 1).bytes = 30852;
Files(74, 1).isdir = false;
Files(74, 1).datenum = 738865.63821759261;
Files(75, 1).name = 'X_pass2.txt';
Files(75, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(75, 1).date = '10-Ara-2022 15:19:02';
Files(75, 1).bytes = 35191;
Files(75, 1).isdir = false;
Files(75, 1).datenum = 738865.63821759261;
Files(76, 1).name = 'X_pass3.txt';
Files(76, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(76, 1).date = '10-Ara-2022 15:19:02';
Files(76, 1).bytes = 40237;
Files(76, 1).isdir = false;
Files(76, 1).datenum = 738865.63821759261;
Files(77, 1).name = 'X_pickup1.txt';
Files(77, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(77, 1).date = '10-Ara-2022 15:19:02';
Files(77, 1).bytes = 42320;
Files(77, 1).isdir = false;
Files(77, 1).datenum = 738865.63821759261;
Files(78, 1).name = 'X_pickup2.txt';
Files(78, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(78, 1).date = '10-Ara-2022 15:19:02';
Files(78, 1).bytes = 38610;
Files(78, 1).isdir = false;
Files(78, 1).datenum = 738865.63821759261;
Files(79, 1).name = 'X_pickup3.txt';
Files(79, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(79, 1).date = '10-Ara-2022 15:19:02';
Files(79, 1).bytes = 39037;
Files(79, 1).isdir = false;
Files(79, 1).datenum = 738865.63821759261;
Files(80, 1).name = 'X_shoot1.txt';
Files(80, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(80, 1).date = '10-Ara-2022 15:19:02';
Files(80, 1).bytes = 25340;
Files(80, 1).isdir = false;
Files(80, 1).datenum = 738865.63821759261;
Files(81, 1).name = 'X_shoot2.txt';
Files(81, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(81, 1).date = '10-Ara-2022 15:19:02';
Files(81, 1).bytes = 30139;
Files(81, 1).isdir = false;
Files(81, 1).datenum = 738865.63821759261;
Files(82, 1).name = 'X_shoot3.txt';
Files(82, 1).folder = ['C:\Users\Asus\Documents\MATLAB\New Folder\proye' ...
                       'cto'];
Files(82, 1).date = '10-Ara-2022 15:19:02';
Files(82, 1).bytes = 22684;
Files(82, 1).isdir = false;
Files(82, 1).datenum = 738865.63821759261;

ans = 'X_shoot3.txt';

